/* 
ENV EXAMPLE
 NEXT_PUBLIC_APP_URL = "http://localhost:3000";
 NEXT_PUBLIC_API_URL = "http://127.0.0.1:8080/api";
 AUTH_SECRET = "420b7a99ab9ab44b1bf27564aca86246";

*/

const NEXT_PUBLIC_APP_URL = process.env.NEXT_PUBLIC_APP_URL;
const NEXT_PUBLIC_API_URL = process.env.NEXT_PUBLIC_API_URL;

const AUTH_SECRET = process.env.AUTH_SECRET;

export { NEXT_PUBLIC_APP_URL, NEXT_PUBLIC_API_URL, AUTH_SECRET };
